version: "3.8"
# This compose file is for running services "like in production" on dev machine.
# But instead of pulling images, we build them locally, so that we could debug Docker builds themselves.

services:
  nginx:
    image: nginx:1.25-alpine
    networks:
      - localNetwork
    ports:
      - "8001:80"
    volumes:
      - ./nginx-local/nginx.local-cors.conf:/etc/nginx/conf.d/default.conf

  backend:
    build:
      context: backend
    networks:
      - localNetwork
    ports:
      - "8000:8000"
    restart: always
    # healthcheck:
    #   test: curl --fail http://localhost:8000/check/health || exit 1
    #   interval: 3s
    #   retries: 50
    #   start_period: 5s
    #   timeout: 5s

  webapp:
    build:
      context: webapp
    networks:
      - localNetwork
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - backend
      #   condition: service_healthy
    environment:
      - WEBAPP_BACKEND_URL=http://localhost:8001
      - WEBAPP_ALLOW_INDEXING=true
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}"

networks:
  localNetwork:
    name: fullstack-k8s-local-build
