zitadel:
  masterkey: x123456789012345678901234567891y
  configmapConfig:
    ExternalDomain: "ecommerce1-auth.prototyping.quest"
    ExternalPort: 443
    ExternalSecure: true
    TLS:
      Enabled: false
    Database:
      Postgres:
        Host: db-postgresql
        Port: 5432
        Database: zitadel
        MaxOpenConns: 20
        MaxIdleConns: 10
        MaxConnLifetime: 30m
        MaxConnIdleTime: 5m
        User:
          Username: postgres
          SSL:
            Mode: disable
        Admin:
          Username: postgres
          SSL:
            Mode: disable
