-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Enum.OrderStatus exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| Order status
-}
type OrderStatus
    = Pending
    | Shipped
    | Delivered
    | Cancelled


list : List OrderStatus
list =
    [ Pending, Shipped, Delivered, Cancelled ]


decoder : Decoder OrderStatus
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "PENDING" ->
                        Decode.succeed Pending

                    "SHIPPED" ->
                        Decode.succeed Shipped

                    "DELIVERED" ->
                        Decode.succeed Delivered

                    "CANCELLED" ->
                        Decode.succeed Cancelled

                    _ ->
                        Decode.fail ("Invalid OrderStatus type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : OrderStatus -> String
toString enum____ =
    case enum____ of
        Pending ->
            "PENDING"

        Shipped ->
            "SHIPPED"

        Delivered ->
            "DELIVERED"

        Cancelled ->
            "CANCELLED"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe OrderStatus
fromString enumString____ =
    case enumString____ of
        "PENDING" ->
            Just Pending

        "SHIPPED" ->
            Just Shipped

        "DELIVERED" ->
            Just Delivered

        "CANCELLED" ->
            Just Cancelled

        _ ->
            Nothing
