apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-service
  namespace: applications
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: web-service
      app.kubernetes.io/part-of: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web-service
        app.kubernetes.io/part-of: app
    spec:
      containers:
        - name: web
          image: ghcr.io/managed-prototypes/fullstack-k8s-webapp:sha-f8f23e0
          imagePullPolicy: IfNotPresent
          # resources:
          #   limits:
          #     memory: 512Mi
          #     cpu: "0.5"
          #   requests:
          #     memory: 128Mi
          #     cpu: "0.2"
          ports:
            - containerPort: 80
          env:
            - name: WEBAPP_BACKEND_URL
              value: "https://test-subdomain-5-api.prototyping.quest"
            - name: WEBAPP_ALLOW_INDEXING
              value: "true"
      imagePullSecrets:
        - name: dockerconfigjson-ghcr
---
apiVersion: v1
kind: Service
metadata:
  namespace: applications
  name: web-service
spec:
  selector:
    app.kubernetes.io/name: web-service
    app.kubernetes.io/part-of: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
