_default:
  @ just --list --unsorted

start:
  #!/bin/sh
  set -eu
  npm start

check-and-build:
  #!/bin/sh
  set -eu
  npm run check-and-build

precommit-fix:
  #!/bin/sh
  set -eu
  npm run precommit-fix
