-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Cart exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import ScalarCodecs


items :
    SelectionSet decodesTo Api.Object.CartItem
    -> SelectionSet (List decodesTo) Api.Object.Cart
items object____ =
    Object.selectionForCompositeField "items" [] object____ (Basics.identity >> Decode.list)


total : SelectionSet ScalarCodecs.UsdAmount Api.Object.Cart
total =
    Object.selectionForField "ScalarCodecs.UsdAmount" "total" [] (ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecUsdAmount |> .decoder)
