-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Order exposing (..)

import Api.Enum.OrderStatus
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import ScalarCodecs


orderId : SelectionSet String Api.Object.Order
orderId =
    Object.selectionForField "String" "orderId" [] Decode.string


createdAt : SelectionSet ScalarCodecs.Timestamp Api.Object.Order
createdAt =
    Object.selectionForField "ScalarCodecs.Timestamp" "createdAt" [] (ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecTimestamp |> .decoder)


items :
    SelectionSet decodesTo Api.Object.OrderItem
    -> SelectionSet (List decodesTo) Api.Object.Order
items object____ =
    Object.selectionForCompositeField "items" [] object____ (Basics.identity >> Decode.list)


status : SelectionSet Api.Enum.OrderStatus.OrderStatus Api.Object.Order
status =
    Object.selectionForField "Enum.OrderStatus.OrderStatus" "status" [] Api.Enum.OrderStatus.decoder


total : SelectionSet ScalarCodecs.UsdAmount Api.Object.Order
total =
    Object.selectionForField "ScalarCodecs.UsdAmount" "total" [] (ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecUsdAmount |> .decoder)


shippingOption :
    SelectionSet decodesTo Api.Union.ShippingOption
    -> SelectionSet decodesTo Api.Object.Order
shippingOption object____ =
    Object.selectionForCompositeField "shippingOption" [] object____ Basics.identity
