-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (..)


type Cart
    = Cart


type CartItem
    = CartItem


type Customer
    = Customer


type CustomerOrder
    = CustomerOrder


type Order
    = Order


type OrderItem
    = OrderItem


type PickupPoint
    = PickupPoint


type Product
    = Product


type ShippingOptionDelivery
    = ShippingOptionDelivery
