-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Scalar exposing (Codecs, Timestamp(..), Unit(..), UsdAmount(..), UsdPrice(..), defaultCodecs, defineCodecs, unwrapCodecs, unwrapEncoder)

import Graphql.Codec exposing (Codec)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode
import Json.Decode as Decode exposing (Decoder)
import Json.Encode as Encode


type Timestamp
    = Timestamp String


type Unit
    = Unit String


type UsdAmount
    = UsdAmount String


type UsdPrice
    = UsdPrice String


defineCodecs :
    { codecTimestamp : Codec valueTimestamp
    , codecUnit : Codec valueUnit
    , codecUsdAmount : Codec valueUsdAmount
    , codecUsdPrice : Codec valueUsdPrice
    }
    -> Codecs valueTimestamp valueUnit valueUsdAmount valueUsdPrice
defineCodecs definitions =
    Codecs definitions


unwrapCodecs :
    Codecs valueTimestamp valueUnit valueUsdAmount valueUsdPrice
    ->
        { codecTimestamp : Codec valueTimestamp
        , codecUnit : Codec valueUnit
        , codecUsdAmount : Codec valueUsdAmount
        , codecUsdPrice : Codec valueUsdPrice
        }
unwrapCodecs (Codecs unwrappedCodecs) =
    unwrappedCodecs


unwrapEncoder :
    (RawCodecs valueTimestamp valueUnit valueUsdAmount valueUsdPrice -> Codec getterValue)
    -> Codecs valueTimestamp valueUnit valueUsdAmount valueUsdPrice
    -> getterValue
    -> Graphql.Internal.Encode.Value
unwrapEncoder getter (Codecs unwrappedCodecs) =
    (unwrappedCodecs |> getter |> .encoder) >> Graphql.Internal.Encode.fromJson


type Codecs valueTimestamp valueUnit valueUsdAmount valueUsdPrice
    = Codecs (RawCodecs valueTimestamp valueUnit valueUsdAmount valueUsdPrice)


type alias RawCodecs valueTimestamp valueUnit valueUsdAmount valueUsdPrice =
    { codecTimestamp : Codec valueTimestamp
    , codecUnit : Codec valueUnit
    , codecUsdAmount : Codec valueUsdAmount
    , codecUsdPrice : Codec valueUsdPrice
    }


defaultCodecs : RawCodecs Timestamp Unit UsdAmount UsdPrice
defaultCodecs =
    { codecTimestamp =
        { encoder = \(Timestamp raw) -> Encode.string raw
        , decoder = Object.scalarDecoder |> Decode.map Timestamp
        }
    , codecUnit =
        { encoder = \(Unit raw) -> Encode.string raw
        , decoder = Object.scalarDecoder |> Decode.map Unit
        }
    , codecUsdAmount =
        { encoder = \(UsdAmount raw) -> Encode.string raw
        , decoder = Object.scalarDecoder |> Decode.map UsdAmount
        }
    , codecUsdPrice =
        { encoder = \(UsdPrice raw) -> Encode.string raw
        , decoder = Object.scalarDecoder |> Decode.map UsdPrice
        }
    }
